name: Mac OS build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    env:
      blank-directory: ./UbiGame_Blank
      bird-directory: ./UbiGame_FlappBird  

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Blank
      run: make
      working-directory: ${{env.blank-directory}}
    - name: Build FlappBird
      run: make
      working-directory: ${{env.bird-directory}}
  
